# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  port: 5435
  host: localhost
  username: postgres
  password: postgres
  database: airborne_weather_statuses_development

test:
  <<: *default
  port: 5435
  host: localhost
  username: postgres
  password: postgres
  database: airborne_weather_statuses_test

production:
  <<: *default
  database: airborne_weather_statuses_production
  username: airborne_weather_statuses
  password: <%= ENV['AIRBORNE_WEATHER_STATUSES_DATABASE_PASSWORD'] %>
